### ISSUE TITLE
Create an affiliation for people imported with no titles to enable organization mapping

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss-labs/rialto-etl#136]
@cmh2166 suggested:
> Generic associated with (parent of employed by)? And question to Profiles about why they include people without affiliations?

A question regarding this behavior was sent to the #sul-cap-collab channel.

**Comment by peetucket** [comment]
Can we get examples of people that this applies to and how many they are

**Comment by justinlittman** [comment]
* 4552 stanford people have no positions because they are affiliated with R001 or an unknown organization.
* 11 stanford people have no positions because they have no titles.

See attached.
[no_positions.log](https://github.com/sul-dlss-labs/rialto-etl/files/2492687/no_positions.log)

**Comment by peetucket** [comment]
I had a chance to speak with Tina today and she said they are going to try and get to the R001 org code and "fix" those, which presumably means ensuring there is an actual organization in the list of orgs (perhaps creating new orgs that don't exist in the process) and then putting the new (or current) org codes in people's profile records instead of this R001 code.  Our problem is that its not likely to happen for our current workcycle.  

So I suppose we could  (1) not include these people at all, (2) leave them unmapped to any organizational unit, or (3) map them to some department called "Unknown".  

The unmapped or unknown position leaves us with the people and their research but makes the filtering by department/school potentially not complete (which seems like a reasonable tradeoff to me for now).

Another possibility is to look into the Directory service (https://uit.stanford.edu/developers/apis/person and https://uit.stanford.edu/node/25188), which should give us the actual organization affiliation, but I am not sure we have the development time to go down this path for now.
