### ISSUE TITLE
what RIALTO source data can we share here (for tests or other)?

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss-labs/rialto-etl#7]
Perhaps @peetucket can let us know?

**Comment by peetucket** [comment]
Good question, for sul-cap fixtures, we've been cautious to avoid leaking public information into github.  Its worth a discussion with the team, but my view was that even technically public information (e.g. names, email addresses, california physician license) would be bad to leak since I didn't want to have Stanford faculty finding their information in a random github repo via a Google search.  Workaround was to do things like include my public info or use filtering tools when checking in VCR cassettes.

**Comment by cmh2166** [comment]
@peetucket so if we take the sul-cap data returned but replace values with ourselves or nonsense points, it should be okay to check in as a fixture (for now)?

**Comment by peetucket** [comment]
yes, also, we got sign off from Clarivate to include a limited number of their results in fixture data for testing purpose, so there aren't IP issues there

**Comment by mjgiarlo** [comment]
@cmh2166 Should we leave this open or do we have the info we need to close this issue?

**Comment by cmh2166** [comment]
We still don’t actually have the information

**Comment by peetucket** [comment]
Is this a question about which data sources we have or the types of data that can be shared publicly?

**Comment by mjgiarlo** [comment]
@cmh2166 created a new rialto_sample_data repo that is private. We will store sample data there.
