### ISSUE TITLE
Implement linking of publications with people data

### ISSUE THREAD

**Issue by peetucket** [sul-dlss-labs/rialto-etl#75]
Pending clarification of how to do this

Blocked by https://github.com/sul-dlss-labs/rialto-etl/issues/108
blocked by #53
blocked by #127

**Comment by jcoyne** [comment]
Blocked by #53

**Comment by mjgiarlo** [comment]
This issue is no longer blocked by #53, as that has been closed.

The work needed to close this issue was partially completed in https://github.com/sul-dlss-labs/rialto-etl/pull/106. What remains is the ability to get the mapped data into SPARQL. This is blocked by work @justinlittman is doing to look into whether a different pattern of transforming to SPARQL is feasible.

**Comment by justinlittman** [comment]
This work is completed. There is still further work on #127, but it is not necessary to close this.
